name: SS-FancyDrops
version: @version@
main: me.ste.stevesseries.fancydrops.FancyDrops
api-version: 1.16
depend: [SS-Kotlin, ProtocolLib]
authors: [SteveTheEngineer]
description: A plugin that lets you customize how your dropped items look in the world

commands:
  fancydropsreload:
    usage: /fancydropsreload
    description: Reloads the plugin configuration

permissions:
  stevesseries.fancydrops.reload:
    default: op
    description: Permission to use the /fancydropsreload command